### ISSUE TITLE
Strange Background appears for stickers and animated emojis

### ISSUE THREAD

**Issue by nasyx-rakeeb** [Giphy/giphy-react-native-sdk#105]
Is there any way we can remove that background from stickers and animated Emojis, it looks too ugly with that background, gifs appear just fine

**Comment by nasyx-rakeeb** [comment]
.

**Comment by pshoniuk** [comment]
Hi @nasyx-rakeeb
Have you tried setting the `showCheckeredBackground` property to `false`? That should remove the background.
