### ISSUE TITLE
Cannot download dependency in yarn registry

### ISSUE THREAD

**Issue by santimuller** [Giphy/giphy-react-native-sdk#127]
## To Reproduce
https://registry.yarnpkg.com/@giphy/react-native-sdk

## Expected behavior
yarn install fails when try to download dependency 

You could reproduce if enter at the following url:
https://registry.yarnpkg.com/@giphy/react-native-sdk/-/react-native-sdk-1.7.0.tgz
or: https://registry.yarnpkg.com/@giphy/react-native-sdk

if you try with another dependency it works! 
https://registry.yarnpkg.com/react-native

- Giphy React Native SDK version: 1.7.0 and any other
- React Native version: 0.69.11
- Platform(s) (iOS, Android, or both?): Both yarn install

## Reproducible Demo
![Captura de pantalla 2023-07-14 a la(s) 17 43 25](https://github.com/Giphy/giphy-react-native-sdk/assets/68720087/95a33dce-dd83-433d-b6a2-7530b61198c0)

**Comment by vinkim** [comment]
I'm getting the same issue running `yarn add @giphy/react-native-sdk`

```warning ../../../package.json: No license field
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.npmjs.org/@giphy%2freact-native-sdk: Not found".
```

But I also did cleanup my local cache, and was running into similar issues with other packages, both on yarnpkg.com and npmjs.org.

npm:
```
404 Not Found - GET https://registry.npmjs.org/@react-native-clipboard%2fclipboard - Not found
```
yarn:
```
error An unexpected error occurred: "https://registry.yarnpkg.com/@react-native-clipboard/clipboard/-/clipboard-1.11.2.tgz: Request failed \"404 Not Found\"".
```

Seems to be an issue with the registries, rather than this package specifically.

**Comment by debragail** [comment]
I think yarn registry is down

**Comment by vinkim** [comment]
@santimuller Seems to be working again now, I guess you can close this.

**Comment by santimuller** [comment]
resolved!
