### ISSUE TITLE
XCode build failing after latest update (3.0.0)

### ISSUE THREAD

**Issue by timothyerwin** [Giphy/giphy-react-native-sdk#142]
## 🐛 Bug Report

<img width="394" alt="Screenshot 2023-09-12 at 4 08 30 PM" src="https://github.com/Giphy/giphy-react-native-sdk/assets/2653209/5dbe4649-8864-40f9-ac4c-77f3217ad818">

## To Reproduce

(Write your steps here:)

Update packages using `ncu -u`

```sh
 @giphy/react-components                      ^8.1.0  →    ^9.0.1
 @giphy/react-native-sdk                      ^2.4.2  →    ^3.0.0
```

## Expected behavior

I expect it to build

## Actual Behavior

Build fails even after cleaning, deleting derived, total rebuild, etc.

## Your Environment

- Giphy React Native SDK version: 3.0.0
- React Native version: "0.72.4
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator iOS 16

**Comment by pshoniuk** [comment]
Hi @timothyerwin, thanks for the report!
Have you tried reinstalling the pods from `ios` folder?
```sh
cd ios/
pod install
```
or
```sh
cd ios/
pod install --repo-update
```
