### ISSUE TITLE
FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by w3company-leo** [Giphy/giphy-react-native-sdk#156]
## 🐛 Bug Report

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':ReactAndroid:bundleLibCompileToJarDebug'.
> Could not determine the dependencies of null.
   > Could not create task ':ReactAndroid:compileDebugKotlin'.
      > Cannot convert the provided notation to a File or URI: [/Users/.../node_modules/react-native/ReactAndroid/build/generated/source/codegen/java].
        The following types/formats are supported:
          - A String or CharSequence path, for example 'src/main/java' or '/usr/include'.
          - A String or CharSequence URI, for example 'file:/usr/include'.
          - A File instance.
          - A Path instance.
          - A Directory instance.
          - A RegularFile instance.
          - A URI or URL instance.
          - A TextResource instance.

## Your Environment

- Giphy React Native SDK version: v3.2.1
- React Native version: v0.70.6
- Platform(s) (iOS, Android, or both?): android (gradle 7.5.1)
- Device info (Simulator/Device? OS version? Debug/Release?):  can't debug build

**Comment by ALexanderLonsky** [comment]
Hey @w3company-leo,
Did you try doing `./gradlew clean`?

If that did not help, could you please provide a minimal reproducible playground/demo?

**Comment by w3company-leo** [comment]
@ALexanderLonsky My gradle was 1.6.x 
after upgrade 1.8.0 it works but in android with https://github.com/gorhom/react-native-bottom-sheet 
touchalbeOpcaity is not work
