### ISSUE TITLE
Gifs don't play

### ISSUE THREAD

**Issue by Tarikmnk** [Giphy/giphy-react-native-sdk#176]
Hi, I installed Giphy and used native bottom sheet to select Gif but Gifs don't play. Also I used GiphyMediaView with ID but it didn't play as well.

I configurations are like;

in App.tsx
GiphySDK.configure({
  apiKey: Constants.giphy_key,
});

<GiphyMediaView
  ref={mediaRef}
  resizeMode={'contain'}
  media={{id: 'Ac0fCix8D3oN7DwCEB'}}
  style={{
    width: '100%',
    aspectRatio: 1,
  }}
/>

- Giphy React Native SDK version: 3.2.4
- React Native version: 0.73.6
- Platform(s): Android
- Device info: Emulator API 33 - Real device API 32 Debug

[gif.webm](https://github.com/Giphy/giphy-react-native-sdk/assets/46998249/e84e4712-ccfd-4b00-b609-3a5f6db44d03)

**Comment by ALexanderLonsky** [comment]
Hey @Tarikmnk,
please refer to [this](https://github.com/Giphy/giphy-react-native-sdk/issues/160#issuecomment-1858459948) answer

**Comment by Nav-kr** [comment]
@Tarikmnk is your issue  was resolved ?
I was facing same issue GIF not playing 
RN version :- 0.73.4 
GIPHY SDK - 3.2.6

**Comment by Tarikmnk** [comment]
@Nav-kr Hey, yes it solved my problem.
