### ISSUE TITLE
Crash on android when start app

### ISSUE THREAD

**Issue by iamvucms** [Giphy/giphy-react-native-sdk#18]
Hello I'm getting this error after install giphy to my react native app. It appears after I start project successfully and open app, then it make my app crash after. Hope your response !!

`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/ExoPlayer$EventListener;
        at com.brentvatne.react.ReactVideoPackage.createViewManagers(ReactVideoPackage.java:28)
        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:850)
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:190)
        at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:158)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:159)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:147)
        at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:191)
        at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:156)
        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:149)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:596)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:566)
        at com.facebook.react.bridge.ReactContext.getNativeModule(ReactContext.java:165)
        at com.swmansion.reanimated.NodesManager.<init>(NodesManager.java:143)
        at com.swmansion.reanimated.ReanimatedModule.getNodesManager(ReanimatedModule.java:100)
        at com.swmansion.reanimated.ReanimatedJSIModulePackage.getJSIModules(ReanimatedJSIModulePackage.java:17)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1256)
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.ExoPlayer$EventListener" on path: DexPathList[[zip file "/data/app/com.__.community-UEb_wIQqkcOxAJ7xSahL2Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.___.community-UEb_wIQqkcOxAJ7xSahL2Q==/lib/arm64, /data/app/___-UEb_wIQqkcOxAJ7xSahL2Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)`

**Comment by 00000111** [comment]
Hello, can you please describe your environment? What JDK version you're using? What is your version of Android SDK? How you've built the project, with `yarn example android`, or from Android Studio?

**Comment by iamvucms** [comment]
Hello @00000111 
Thanks for replying 
I'm trying to update gradle files and settings file on android folder to match with your example project, now I'm facing this issue:
`* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :giphyreactnativesdk.
     Required by:
         project :app
      > Unable to find a matching configuration of project :giphyreactnativesdk:
          - None of the consumable configurations have attributes.`
          
 Here is react native info output
 `System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 524.46 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`
   
   JAVAC
   > javac -version
> javac 11.0.11
   
   Here is settings.gradle

>    rootProject.name = 'xxxx'
> 
> include ':react-native-incall-manager'
> project(':react-native-incall-manager').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-incall-manager/android')
> include ':@gurukumparan_react-native-android-inapp-updates'
> project(':@gurukumparan_react-native-android-inapp-updates').projectDir = new File(rootProject.projectDir, '../node_modules/@gurukumparan/react-native-android-inapp-updates/android')
> include ':@react-native-community_cameraroll'
> project(':@react-native-community_cameraroll').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-community/cameraroll/android')
> apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
> apply from: '../node_modules/react-native-unimodules/gradle.groovy'
> includeUnimodulesProjects()
> include ':giphyreactnativesdk'
> project(':giphyreactnativesdk').projectDir = new File(rootProject.projectDir, '../../android')
> include ':react-native-webview'
> project(':react-native-webview').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-webview/android')
> include ':react-native-onesignal'
> project(':react-native-onesignal').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-onesignal/android')
> include ':WebRTCModule', ':app'
> project(':WebRTCModule').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-webrtc/android')
> include ':react-native-vector-icons'
> project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')
> include ':react-native-reanimated'
> project(':react-native-reanimated').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-reanimated/android')
> include ':react-native-video'
> project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
> include ':react-native-maps'
> project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/lib/android')
> 
> include ':app'
Here is android/build.gradle
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        supportLibVersion = "29.0.0"
        firebaseVersion = "17.+"
        googlePlayServicesVersion = "16.+"
        androidMapsUtilsVersion = "+"
        kotlinVersion = "+"
        firebaseMessagingVersion = "21.1.0"
    }
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
        maven { url 'https://plugins.gradle.org/m2/' }
        maven { url 'https://maven.google.com' }
        
    }
    dependencies {
        classpath('com.android.tools.build:gradle:4.0.0')
        classpath 'com.google.gms:google-services:4.3.2'
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.9, 0.99.99]'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        // Add jitpack repository (added by tipsi-stripe)
        maven { url "https://jitpack.io" }
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        maven { url 'https://maven.google.com' }
        google()
        jcenter()
      	maven {
      	    url "https://sdks.instabug.com/nexus/repository/instabug-cp"
       	}
        
      }
}

configurations.all {
    resolutionStrategy {
        force 'com.facebook.android:facebook-android-sdk:4.22.1'
    }
    resolutionStrategy.eachDependency {details ->
        def requested = details.requested
        if (requested.group == 'com.google.android.gms') {
            details.useVersion '12.0.1'
        }
        if (requested.group == 'com.google.firebase') {
            details.useVersion '12.0.1'
        }
    }
}

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 29
                buildToolsVersion "29.0.3"
            }
        }
        if (project.name.contains('react-native-image-picker')) {
            buildscript {
                repositories {
                    jcenter()
                    maven { url "https://dl.bintray.com/android/android-tools/"  }
                }
            }
        }
    }
}
task clean(type: Delete) {
    delete rootProject.buildDir
}
```
And final android/app/build.gradle
```
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
apply plugin: "com.android.application"
apply from: '../../node_modules/react-native-unimodules/gradle.groovy'

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // https://facebook.github.io/react-native/docs/performance#enable-the-ram-format
 *   bundleCommand: "ram-bundle",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */
addUnimodulesDependencies(
    exclude: [
      'expo-constants',
      'expo-permissions',
      'expo-image-picker',
      'expo-location'
    ],
)

project.ext.react = [
        entryFile: "index.js",
        enableHermes: true,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = true

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    dexOptions {
        javaMaxHeapSize "3g"
    }

    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        missingDimensionStrategy 'react-native-camera', 'general'
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
        applicationId "com.xxxx.community"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 75
        versionName "75.0"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }

    packagingOptions {
        pickFirst '**/armeabi-v7a/libc++_shared.so'
        pickFirst '**/x86/libc++_shared.so'
        pickFirst '**/arm64-v8a/libc++_shared.so'
        pickFirst '**/x86_64/libc++_shared.so'
        pickFirst '**/x86/libjsc.so'
        pickFirst '**/armeabi-v7a/libjsc.so'
    }
}

configurations.all {
    resolutionStrategy {
        force 'com.facebook.android:facebook-android-sdk:4.22.1'
        force 'com.android.support:support-v4:27.1.0'
    }

    resolutionStrategy.eachDependency {details ->
        def requested = details.requested
        if (requested.group == 'androidx.annotation') {
            details.useVersion '1.0.0'
            exclude group: 'androidx.annotation'
        }

        if (requested.group == 'androidx.arch.core') {
            details.useVersion '2.0.0'
            exclude group: 'androidx.arch.core'
        }
    }
}
dependencies {
    implementation'com.facebook.soloader:soloader:0.9.0+'
    implementation project(':react-native-webview')
    implementation project(':react-native-onesignal')
    implementation project(':react-native-vector-icons')
    implementation project (':react-native-video')
    implementation project(':@react-native-firebase_app')
    implementation project(':@react-native-firebase_analytics')
    implementation project(':react-native-paypal-lib')
    implementation project(':react-native-splash-screen')
    implementation project(':react-native-image-crop-picker')
    implementation 'com.google.firebase:firebase-messaging:21.1.0'
    implementation('com.google.firebase:firebase-analytics:17.2.1')
    compile ('com.google.android.gms:play-services-gcm:10.0.1') {
        force = true;
    }
    compile project(':WebRTCModule')
    implementation project(':react-native-maps')
    implementation project(':react-native-image-picker')
    implementation project(':@terrylinla_react-native-sketch-canvas')
    implementation project(':react-native-gesture-handler')
    implementation project(':react-native-contacts')
    implementation project(':@react-native-community_async-storage')
    implementation project(':react-native-svg')
    implementation project(':react-native-reanimated')
    implementation project(':rn-fetch-blob')
    compile (project(':react-native-push-notification')) {
        exclude group: "com.google.android.gms", module: "play-services-gcm"
        exclude group: "com.google.firebase"
    }
    implementation 'com.google.android.gms:play-services-gcm:17.0.0'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.firebase:firebase-core:17.2.2'
    implementation 'com.android.support:design:27.1.0'
    implementation (project(':tipsi-stripe'))
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:0.60.5"  // From node_modules
    implementation 'androidx.appcompat:appcompat:1.3.0-alpha01'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
//    implementation 'com.android.support:support-v4:+'

    implementation 'com.android.support:support-v13:28.0.0'

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
    implementation project(':giphyreactnativesdk')
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
apply plugin: 'com.google.gms.google-services'
apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

```

**Comment by iamvucms** [comment]
A news, after I modified settings.gradle

> include ':giphyreactnativesdk'
> project(':giphyreactnativesdk').projectDir = new File(rootProject.projectDir, '../node_modules/@giphy/react-native-sdk/android')

I'm able to build and open, but it' crash after open with same error as I described on title of issue

**Comment by iamvucms** [comment]
@00000111  New point, After purged react-native-video, I'm able to start and open app. Please help me check it, perhaps there are some conflict between exoplayer in react-native-video and your dependecies

**Comment by 00000111** [comment]
@iamvucms Sorry for the delayed response, `exoplayer` is used by GiphyVideoView under the hood, so probably this is where the conflict takes place. I'll check it and return to you a little bit later

**Comment by ALexanderLonsky** [comment]
hello @iamvucms ,
thanks for your patience.
This crash is related to the `Exoplayer` dependency conflict.
`react-native-video` uses an older Exoplayer version than `Giphy` SDK does.

Gradle `resolutionStrategy` won't help here because of a breaking change in the newer `Exoplayer` version.

Unfortunately, we have to wait for `react-native-video` to update their `Exoplayer` dependency version.
They have a [request](https://github.com/react-native-video/react-native-video/issues/2474) to update it.

**Comment by pshoniuk** [comment]
ExoPlayer has been updated in the latest versions of react-native-video. Thus, the [Giphy RN SDK v1.2.0](https://github.com/Giphy/giphy-react-native-sdk/releases/tag/v1.2.0) and [react-native-video v5.2.0](https://github.com/react-native-video/react-native-video/releases/tag/v5.2.0) should now work correctly together.
