### ISSUE TITLE
How to change empty results text "No stickers found" 

### ISSUE THREAD

**Issue by Ibrahim-Arif** [Giphy/giphy-react-native-sdk#183]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I'm using the `GiphyGridView` component to render the results of the searched string, but if no result is found, the component shows a "No stickers found" message. Which is good, however, my app is in Spanish language and needs to change this message to "No se encontraron stickers" but I couldn't find any prop to change this text

No prop found here: https://github.com/Giphy/giphy-react-native-sdk/blob/HEAD/docs/api.md#giphygridview

I also asked Gemini and it was also not able to give a correct solution 
https://g.co/gemini/share/ec77f54e2dc5
the property Gemini suggested `renderEmpty` does not exist in the docs.

**Comment by ALexanderLonsky** [comment]
Hey @Ibrahim-Arif,
Thanks for flagging this. 
We don't support localization now, but I have passed this request on to my team. 
I'll keep you posted.

**Comment by ALexanderLonsky** [comment]
@Ibrahim-Arif,
We have released version [3.3.0](https://github.com/Giphy/giphy-react-native-sdk/releases/tag/v3.3.0), which addresses the localization issue. You can find the documentation [here](https://github.com/Giphy/giphy-react-native-sdk/blob/main/docs/localization.md).
