### ISSUE TITLE
Error on launch IOS

### ISSUE THREAD

**Issue by Sondago** [Giphy/giphy-react-native-sdk#19]
Hi, i have a problem with giphy-react-native-sdk in IOS. Build works fine but when launching my app, it stucks on launchscreen and i got log error : "Fatal error: Unexpectedly found nil while unwrapping an Optional value: file giphy_react_native_sdk/RNGiphyDialog.swift, line 60"

Can you help me please ?

**Comment by pshoniuk** [comment]
Hi @Sondago, thanks for the report!
Should be fixed in version [v1.0.2](https://github.com/Giphy/giphy-react-native-sdk/releases/tag/v1.0.2)

**Comment by Sondago** [comment]
Thank's you very much, it's work now
