### ISSUE TITLE
Version 3.3.0 not published to NPM

### ISSUE THREAD

**Issue by Calinteodor** [Giphy/giphy-react-native-sdk#196]
## 🐛 Bug Report

When is this version going to be available?

## To Reproduce

(Write your steps here:)

1. Step 1...
1. Step 2...
1. Step 3...

## Expected behavior

(Write what you thought would happen.)

## Actual Behavior

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- Giphy React Native SDK version: FILL THIS OUT
- React Native version: FILL THIS OUT
- Platform(s) (iOS, Android, or both?): FILL THIS OUT
- Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by ALexanderLonsky** [comment]
Hey @Calinteodor, thanks for flagging this!
This version is already available on NPM.
