### ISSUE TITLE
Upgrade Giphy iOS SDK to at least 2.2.11 for Xcode 16/iOS 18 compatibility

### ISSUE THREAD

**Issue by MegaMaddin** [Giphy/giphy-react-native-sdk#198]
## 🐛 Bug Report

Using the latest version of the RN SDK crashes on Xcode16 / iOS 18 when using `GiphyGridView`. This was fixed with the iOS SDK release [2.2.11](https://github.com/Giphy/giphy-ios-sdk/releases/tag/v2.2.11).

## To Reproduce

1. Build app with Xcode 16 for an iOS 18 simulator
1. Open a view including `GiphyGridView` as a child
1. App crashes when view tries to display images

## Expected behavior

Using the SDK shouldn't lead crash.

## Actual Behavior

Using the SDK lead to a crash.

## Your Environment

- Giphy React Native SDK version: 3.3.0
- React Native version: 0.72.14
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): Sim/Device

## Reproducible Demo

1. Build app with Xcode 16 for an iOS 18 simulator
1. Open a view including `GiphyGridView` as a child
1. App crashes when view tries to display images

## Fix

Raising the pod dependency of `Giphy` to 2.2.11 fixes the issue.

**Comment by ALexanderLonsky** [comment]
[The new version](https://github.com/Giphy/giphy-react-native-sdk/releases/tag/v3.3.1) has been released.

**Comment by MegaMaddin** [comment]
Awesome @ALexanderLonsky - feel free to resolve this issue!
