### ISSUE TITLE
Giphy Dialog Attribution images

### ISSUE THREAD

**Issue by TomAtterton** [Giphy/giphy-react-native-sdk#199]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Shouldn't we add the Attribution images to the dialog if it's required to get a production key?

### Motivation 🔦

Simplify production submissions

**Comment by cgmaier** [comment]
hey @TomAtterton, 

If you're using the dialogue or have a custom search bar with the text, "Search GIPHY",  that should be sufficient to meet our attribution requirements. Ideally, developers will also use the `GPHMediaView` for share contexts outside of the search experience, which briefly presents a small GIPHY watermark in the corner before fading out, but we understand this view isn't great for all use cases.  

Was your production key rejected? Let us know and we can take a look.

**Comment by mrdanielm** [comment]
> hey @TomAtterton,
> 
> If you're using the dialogue or have a custom search bar with the text, "Search GIPHY", that should be sufficient to meet our attribution requirements. Ideally, developers will also use the `GPHMediaView` for share contexts outside of the search experience, which briefly presents a small GIPHY watermark in the corner before fading out, but we understand this view isn't great for all use cases.
> 
> Was your production key rejected? Let us know and we can take a look.

I've just requested a production key using the approach you've suggested above, "Search GIPHY" and the GIPHY watermark that fades out. Let me know if that's suitable

**Comment by TomAtterton** [comment]
@cgmaier Thanks I sent this when I submitted just incase there was something I needed to add but indeed like you said this was enough for approval 🥳  

I will close this now thanks for quick response!

**Comment by MS0015** [comment]
![Image](https://github.com/user-attachments/assets/dc79f2a4-729e-4b8b-85a7-678d6747753c)

I requested a production key for my app, which uses GiphyDialog. However, my request was rejected with the following message:

"Thanks for your interest in using our API. After review, it looks like you need to include the approved 'Powered by GIPHY' attribution. You can download the approved assets here: https://media.giphy.com/giphy-attribution-marks.zip. Once you make that fix, please edit your application and attach a video capture of the user experience for adding GIFs in your app."

However, GiphyDialog does not provide a prop to add or remove the attribution. How can I get my request approved?
