### ISSUE TITLE
Error: Exception in HostObject::get for prop 'RTNGiphyDialogModule'

### ISSUE THREAD

**Issue by PROda221** [Giphy/giphy-react-native-sdk#200]
Hi everyone, 
I am using RN 0.74.3. I used giphy sdk package at version 3.3.1 but saw all gifs were static (not playing)

So I referred to [this](https://github.com/Giphy/giphy-react-native-sdk/issues/160#issuecomment-1858459948) change (i.e, copied resolution change to build.gradle (app) above dependencies)

After such change, I am now facing this issue:- 
Error: Exception in HostObject::get for prop 'RTNGiphyDialogModule': java.lang.NoSuchMethodError: No direct method <init>(Lcom/giphy/sdk/ui/themes/GPHTheme;[Lcom/giphy/sdk/ui/GPHContentType;ZZLcom/giphy/sdk/core/models/enums/RatingType;Lcom/giphy/sdk/core/models/enums/RenditionType;Lcom/giphy/sdk/core/models/enums/RenditionType;Lcom/giphy/sdk/core/models/enums/RenditionType;ZILcom/giphy/sdk/ui/GPHContentType;ZZZZLcom/giphy/sdk/ui/drawables/ImageFormat;ZFZILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lcom/giphy/sdk/ui/GPHSettings; or its super classes (declaration of 'com.giphy.sdk.ui.GPHSettings' appears in /data/app/~~CsonlMbIpkPe_fVXvLsvKQ==/com.just_ask-vvEpg2-fehg-q2KwBA555Q==/base.apk!classes6.dex), js engine: hermes

Am I missing something?

**Comment by ALexanderLonsky** [comment]
Hey @PROda221,
Did you include `com.giphy.sdk:ui:2.3.15`? 
This is the latest Android SDK version, where we introduced new properties.

**Comment by PROda221** [comment]
This is what I did in android build.gradle (app)

![image](https://github.com/user-attachments/assets/e6282363-aa2a-4cb8-8a65-2fc2b554b063)

**Comment by ALexanderLonsky** [comment]
you need to replace `2.3.13` with `2.3.15`

**Comment by PROda221** [comment]
Yup this works! Thanks :)
