### ISSUE TITLE
explicit or implicit dependency react-native-giphy

### ISSUE THREAD

**Issue by sivamurthinaroji** [Giphy/giphy-react-native-sdk#202]
Gradle detected a problem with the following location: '/Users/Siva-vempower/Documents/Meethour repos/tttaaaa/Meethour-Web-MobileApps'.
    
    Reason: Task ':sdk:bundleReleaseJsAndAssets' uses this output of task ':react-native-giphy:packageReleaseResources' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':react-native-giphy:packageReleaseResources' as an input of ':sdk:bundleReleaseJsAndAssets'.
      2. Declare an explicit dependency on ':react-native-giphy:packageReleaseResources' from ':sdk:bundleReleaseJsAndAssets' using Task#dependsOn.
      3. Declare an explicit dependency on ':react-native-giphy:packageReleaseResources' from ':sdk:bundleReleaseJsAndAssets' using Task#mustRunAfter.

**Comment by ALexanderLonsky** [comment]
Hey @sivamurthinaroji,

Could you please provide the steps to reproduce?

and 
#### Your Environment
- Giphy React Native SDK version
- React Native version

**Comment by sivamurthinaroji** [comment]
"@giphy/react-native-sdk": "^2.3.0", 
"react-native": "0.73.8",

**Comment by ALexanderLonsky** [comment]
please use the following version:

`"@giphy/react-native-sdk": "^3.3.1"`

Additionally, make sure to follow the [instructions](https://github.com/Giphy/giphy-react-native-sdk/blob/main/docs/getting-started.md#gifs-are-not-playing-on-android).
