### ISSUE TITLE
App is crashed when GiphyGridView search content is null

### ISSUE THREAD

**Issue by illlama** [Giphy/giphy-react-native-sdk#204]
## 🐛 Bug Report
I’m using GiphyGridView as follows:
```
 <GiphyGridView
          theme={GiphyTheme}
          spanCount={4}
          content={GiphyContent.search({ searchQuery: searchQuery, rating: 'pg-13', mediaType: memeType })}
          cellPadding={10}
          style={{ flex: 1, marginTop: 24 }}
          onMediaSelect={(e) => handleMediaSelect(e.nativeEvent.media.data)}
        />
```
But when searchQuery value to be random string like 'oqdwjkdw', app is crashed.
So I tried to aviod this error by using onContentUpdate props to count result and set loading state but eventually failed.

## To Reproduce

(Write your steps here:)

	1.	Render GiphyGridView in a React Native project as shown in the code snippet.
	2.	Pass a search query to GiphyContent.search.
	3.     Type random string like 'dqwdioeqwjdoi' to searchQuery  
	4.	My code is shutdown at this moment.

## Expected behavior

Can I set a component when search result is empty? 
(Except this error, everything is perfect!)

## Actual Behavior

When GiphyGridView is loaded with a search query that returns no results (for example, entering a random string like “djioqjdwiojdq”), the app crashes instead of handling the “no results” case gracefully. This crash occurs every time an uncommon or meaningless query with no matching results is executed. I would like the SDK to handle empty results without causing the app to shut down, ideally by displaying a “No results found” message or leaving the grid empty.

## Your Environment

- Giphy React Native SDK version: "^3.2.6"
- React Native version: "^0.72.5"
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): iPhone 14 pro

## Reproducible Demo

You can reproduce the issue by setting up a basic React Native app with GiphyGridView configured as shown in the code snippet above.

**Comment by ALexanderLonsky** [comment]
Hey @illlama,
I'm sorry to hear that. This issue is indeed known when compiling a project with Xcode 16. We’ve resolved it in the iOS SDK and released a [new version](https://github.com/Giphy/giphy-react-native-sdk/releases/tag/v3.3.1) of the React Native SDK that uses the updated iOS SDK with the fix. 
Please update to [this](https://github.com/Giphy/giphy-react-native-sdk/releases/tag/v3.3.1) version, and it should work as expected, displaying 
`GIFs not found.`
