### ISSUE TITLE
CocoaPods could not find compatible versions for pod "giphy-react-native-sdk"

### ISSUE THREAD

**Issue by eramudeep** [Giphy/giphy-react-native-sdk#25]
followed the [installation guide ](https://github.com/Giphy/giphy-react-native-sdk/blob/main/docs/getting-started.md#installation)

> Got below error

 
`
[!] CocoaPods could not find compatible versions for pod "giphy-react-native-sdk":
  In Podfile:
    giphy-react-native-sdk (from `../node_modules/@giphy/react-native-sdk`)

Specs satisfying the `giphy-react-native-sdk (from `../node_modules/@giphy/react-native-sdk`)` dependency were found, but they required a higher minimum deployment target.
`

**Need Help**

**Comment by longvi2810** [comment]
same issue

**Comment by pshoniuk** [comment]
@longvi2810 Did you try to run `pod update` from the ios folder?

**Comment by mrksohag** [comment]
Update Podfile iOS Version 10.2
`platform :ios, '10.2'`

**Comment by pshoniuk** [comment]
This issue seems to be related to an incorrect version of the deployment target in Podfile. The minimum version of the deployment target is `10.2`.  You can read more about the requirements [here](https://github.com/Giphy/giphy-react-native-sdk/blob/main/docs/getting-started.md#requirements).
