### ISSUE TITLE
[android] Crash on didLongPressCell in Giphy Grid View 

### ISSUE THREAD

**Issue by M1ST4KE** [Giphy/giphy-react-native-sdk#33]
In file `android/src/main/java/com/giphyreactnativesdk/GiphyGridViewManager.kt` in method `getSearchGridCallback` are not implemented callbacks `didLongPressCell` and `didTapUsername`, which instead of doing nothing, are throwing `TODO("not implemented")` exception.

**Comment by pshoniuk** [comment]
Hi @M1ST4KE, thanks for the report and work on the fix!
It should be fixed in [v1.1.1](https://github.com/Giphy/giphy-react-native-sdk/releases/tag/v1.1.1)
