### ISSUE TITLE
iOS Builds Fail

### ISSUE THREAD

**Issue by haleyngonadi** [Giphy/giphy-react-native-sdk#37]
I'm unable to run my app after installing this package. 

** BUILD FAILED **

The following build commands failed:
        CompileSwift normal x86_64 /Users/user/Apps/AppName/node_modules/@giphy/react-native-sdk/ios/Utils/GPHMedia.swift
        CompileSwift normal x86_64 /Users/user/Apps/AppName/node_modules/@giphy/react-native-sdk/ios/RNGiphyDialog.swift
        CompileSwift normal x86_64 /Users/user/Apps/AppName/node_modules/@giphy/react-native-sdk/ios/RNGiphyGridView.swift
        CompileSwift normal x86_64 /Users/user/Apps/AppName/node_modules/@giphy/react-native-sdk/ios/RNGiphyGridViewManager.swift
        CompileSwift normal x86_64 /Users/user/Apps/AppName/node_modules/@giphy/react-native-sdk/ios/RNGiphyMediaView.swift
        CompileSwift normal x86_64 /Users/user/Apps/AppName/node_modules/@giphy/react-native-sdk/ios/RNGiphyMediaViewManager.swift
        CompileSwift normal x86_64 /Users/user/Apps/AppName/node_modules/@giphy/react-native-sdk/ios/RNGiphySDK.swift
        CompileSwift normal x86_64 /Users/user/Apps/AppName/node_modules/@giphy/react-native-sdk/ios/Utils/RNGiphyTypeExtensions.swift
        CompileSwift normal x86_64 /Users/user/Apps/AppName/node_modules/@giphy/react-native-sdk/ios/RNGiphyVideoManager.swift
        CompileSwift normal x86_64 /Users/user/Apps/AppName/node_modules/@giphy/react-native-sdk/ios/RNGiphyVideoView.swift
        CompileSwift normal x86_64 /Users/user/Apps/AppName/node_modules/@giphy/react-native-sdk/ios/RNGiphyVideoViewManager.swift
        CompileSwift normal x86_64 /Users/user/Apps/AppName/node_modules/@giphy/react-native-sdk/ios/Utils/RNSDKInfo.swift
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(13 failures)

info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The terminal process "zsh '-c', 'yarn run ios'" terminated with exit code: 1.

**Comment by pshoniuk** [comment]
Hello @haleyngonadi, could you please describe your environment? What version of Xcode are you using, and for which version of iOS are you compiling the app?

**Comment by haleyngonadi** [comment]
Hi @pshoniuk, sorry about that. here's the info: 

> What version of Xcode are you using
12.4

Which version of iOS are you compiling the app?
> 14.5.1

**Comment by pshoniuk** [comment]
@haleyngonadi  Could you please also share the output of "yarn ios run --verbose"? This might help determine the root of the problem because I can't reproduce this issue in my environment.

**Comment by pierroo** [comment]
I am facing the same issue as you @haleyngonadi ; did you find a solution yet? :/

And when I try to build from Xcode rather than CLI, I get the following error:


<img width="960" alt="Capture d’écran 2021-11-19 à 16 51 20" src="https://user-images.githubusercontent.com/17619412/142651919-e6233a1f-faee-4fff-a5b7-c6d5d86f262b.png">


I have the following Podfile:

====
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'app' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'app_newTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
```

====

I read somewhere that Giphy requires use_framework! in Podfile to work; is that confirmed even for latest react native version? (0.66) (using gipfhy native sdk 1.1.1)
=> I need flipper to work with firebase, so use_framework is not an option;

Can you please help @pshoniuk ?
I have been looking around for hours and still unable to find a solution :/

**Comment by haleyngonadi** [comment]
@pierroo Unfortunately I couldn't get it to work so I switched over to [react-native-gif-search](https://github.com/Thanasis1101/react-native-gif-search), and it works great!

**Comment by pierroo** [comment]
Thank you for answering @haleyngonadi ; that is kinda sad news considering Giphy works perfectly on web and android; and gif-search feels much less native. :/

If you happen to pass by @pshoniuk with some more infos or confirmation that in its current state Giphy just cannot work on iOS that would help me move on :)

**Comment by pshoniuk** [comment]
Hey @pierroo! Thank you for such a detailed report. It looks like we have [a problem with XCode 12.5](https://forums.swift.org/t/xcode-12-5-rc-no-such-module-concurrency/47603). I will check the details and come back later with an update. But for now, to get the Giphy RN SDK working, you can try updating your XCode to the latest version. This works for my playground, which I made based on your comments.

**Comment by pierroo** [comment]
Thank you @pshoniuk for your answer: if you tell me it works with latest version of XCode, then it's totally fine with me I will just update, I was afraid of a scarier answer. :)

I will update and edit this message once I tried it.
