### ISSUE TITLE
cellPadding prop in GiphyGridView not working for iOS

### ISSUE THREAD

**Issue by Hyzam-Ali** [Giphy/giphy-react-native-sdk#40]
The cellPadding is not providing spacing between rendered GIFs irrespective of the value provided for iOS. The same issue is reproducible in Example(https://github.com/Giphy/giphy-react-native-sdk/tree/main/example) App as well.

Steps to reproduce:
 -  Add a GiphyGridView to your view
 - set cellPadding prop of GiphyGridView to any non zero value
 - run the application for both iOS and Android
 - observation: cellPadding is present for Android while the same is not present for iOS

**Comment by pshoniuk** [comment]
Hi @Hyzam-Ali, thanks for the report!

Would you please specify what number you were trying to set for the `cellPadding` prop? Since it seems that the Giphy iOS SDK only accepts values from 0 to 12, these values work for me.

**Comment by Hyzam-Ali** [comment]
Yeah, the issue is solved if the value provided is in range [0, 11]. Please update the Documentation to include this point.
