### ISSUE TITLE
new NativeEventEmitter() warning

### ISSUE THREAD

**Issue by pierroo** [Giphy/giphy-react-native-sdk#43]
Hello,

I am getting the following warning with your sdk:

`new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method. 

on React Native 0.66.0
@giphy/react-native-sdk v1.1.1

using the same code as your template:

```
useEffect(() => {
    const handler = (e) => {
      console.log(e.media.url)
      GiphyDialog.hide()
    }
    const listener = GiphyDialog.addListener(
      GiphyDialogEvent.MediaSelected,
      handler
    )
    GiphyDialog.configure({
      rating: 'PG',
      theme: theme
    })
    return () => {
      listener.remove()
    }
  }, [])
```

I wonder if that's a problem or not? (it works in spite of this warning, but you might wanna know...)

**Comment by pshoniuk** [comment]
Hi @pierroo, thanks for the report!

This should be fixed in version [v1.2.0](https://github.com/Giphy/giphy-react-native-sdk/releases/tag/v1.2.0)
