### ISSUE TITLE
Feature request: Need play and pause in GiphyMediaView

### ISSUE THREAD

**Issue by dreamGitBhargav** [Giphy/giphy-react-native-sdk#44]
While working with Andorid SDK we have GifView class by using GifView we can achieve play/pause in native andorid GIF image.

How can we achieve same with react native SDK?

**Comment by dreamGitBhargav** [comment]
Please, let me know if you need more details on this

Thanks @pshoniuk

**Comment by pshoniuk** [comment]
@dreamGitBhargav This feature will be released in an upcoming release. When it does, I will update the status here.

**Comment by dreamGitBhargav** [comment]
We wanted to release our RN app with play/pause feature in GIF image
Is there any ETA for releasing this feature? @pshoniuk

**Comment by pshoniuk** [comment]
This feature should be released tomorrow.

**Comment by pshoniuk** [comment]
The play/pause feature was released in [v1.3.0](https://github.com/Giphy/giphy-react-native-sdk/releases/tag/v1.3.0) ([read more](https://github.com/Giphy/giphy-react-native-sdk/blob/main/docs/api.md#giphymediaview) about the new API).
@dreamGitBhargav

**Comment by dreamGitBhargav** [comment]
Thanks @pshoniuk
