### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by orange-day** [Giphy/giphy-react-native-sdk#45]
I am always grateful for your hard work.

* configuration
  - xcode : 13.1
  - giphy-react-native-sdk: 1.2.0
  - react-native: 0.61.5

* issue
giphy-react-native-sdk `1.2.0` is installed  and then execute 'pod install' in 'iOS' folder.
After the following message is displayed.

* build message

  [!] The following Swift pods cannot yet be integrated as static libraries:

  The Swift pod `giphy-react-native-sdk` depends upon `React-Core`, which does not define modules. To opt into those 
  targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may 
  set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

* `:modular_headers => true` didn't work.

Thank you for your all effort again.

**Comment by pshoniuk** [comment]
Hi @orange-day, thanks for the report!

I reproduced this issue on the playground I made based on your comments. For me, both options fixed the error:
1) I replaced this line `pod 'React-Core', :path => '../node_modules/react-native/` with `pod 'React-Core', :path => '../node_modules/react-native/', :modular_headers => true` in my Porfile
2)  I've added `use_modular_headers!` in the first line of my Podfile

Could you try checking out these solutions when you get a chance?

**Comment by orange-day** [comment]
Hi `@pshoniuk`, thanks for your best effort 😄 

With your suggestion, we succeeded with the following additional work.
Thank you very much.

* additional work
- Targets > General > Frameworks, Libraries, and Embedded Content > (+) GiphyUISDK.xcframework
