### ISSUE TITLE
`syncAutoPlay` makes the app crash on iOS

### ISSUE THREAD

**Issue by dommangetnicolas** [Giphy/giphy-react-native-sdk#46]
## 🐛 Bug Report

Getting an error randomly with `syncAutoPlay` method in `giphy-react-native-sdk`. This issue was very hard to reproduce in our app, and we don't have a lot of logs. We are using https://rollbar.com (Similar to Sentry) and the maximum we get is `EXC_BAD_ACCESS (SIGBUS): Application terminated`. Hopefully I was able to reproduce the crash once in development mode and got this (from `node_modules/@giphy/react-native-sdk/ios/RNGiphyVideoView.swift`):

![Screenshot 2021-12-07 at 14 02 51](https://user-images.githubusercontent.com/46563166/145034044-a1c5da95-f25d-4949-bce3-fe12d9cb41de.png)

In our opinion, it happens only sometimes on Clips (Gif with sound)

## To Reproduce

Sorry to don't have more details. Don't hesitate to contact me or the Feels team.

## Expected behavior

Run Giphy SDK without having crashes.

## Actual Behavior

Crashes sometimes with Clips. And we thinks it happens since many weeks/months.

## Your Environment

- Giphy React Native SDK version: `1.2.0` (Updated this morning, was the same behaviour with `1.1.1`
- React Native version: `0.66.0`
- Platform(s) (iOS, Android, or both?): `iOS`
- Device info (Simulator/Device? OS version? Debug/Release?): `Simulator and real devices` `All iOS versions` `Debug and Release`

## Reproducible Demo

`<GiphyVideoView
            media={{ id: mediaInfo.id }}
            muted={!isLast}
            autoPlay={true}
            style={[styles.videoView, style]}
          />`

**Comment by pshoniuk** [comment]
Hi @dommangetnicolas, thanks for the report!

It's hard to find the root of the issue. But we recently released [v1.3.0](https://github.com/Giphy/giphy-react-native-sdk/releases/tag/v1.3.0) with several updates for the `GiphyVideoView` component that could potentially fix this problem. I'm currently leaving this issue active to see if the problem is fixed or to get more information otherwise.

**Comment by dommangetnicolas** [comment]
Hi @pshoniuk, thanks for the update!

I'll upgrade the SDK this afternoon. I hope it will fix our issues, we'll tell you.

Thanks!

**Comment by dommangetnicolas** [comment]
Hi @pshoniuk,

I am going back to you as we upgraded the SDK but still get crashes. We plan to remove it from the app as it blocks us t o release.

Here is the error we was able to get from XCode with simulator this morning:
![Screenshot 2021-12-09 at 12 25 09](https://user-images.githubusercontent.com/46563166/145387898-96be445a-69c0-4b38-9e99-c7d06b77b824.png)

Many thanks!

**Comment by pshoniuk** [comment]
Thank you for the information. We will continue to investigate and try to replicate this in our environment. If we get any new information, I will post it here.

**Comment by ethoman** [comment]
In a similar boat. We have had these crashes in 1.4.1 and 1.5.0.

**Comment by pshoniuk** [comment]
Hi @dommangetnicolas. We recently released Giphy RN SDK [1.7.0](https://github.com/Giphy/giphy-react-native-sdk/releases/tag/v1.7.0). This release includes fixes and performance improvements for the GiphyVideoView component and potentially fixes the problem described here. Please try this version when you get a chance.
