### ISSUE TITLE
Request to update internal dependency on Exoplayer to v2.16

### ISSUE THREAD

**Issue by Hyzam-Ali** [Giphy/giphy-react-native-sdk#48]
Please update the exoplayer internally used from 2.13.3 to 2.16

**Comment by pshoniuk** [comment]
Hey @Hyzam-Ali! We tested ExoPlayer 2.16 with the Android team. It looks like this version has a lot of changes compared to 2.13. So this will not be a simple change. First of all, the Android team will make the necessary changes in the Giphy Android SDK, and then we will update the ExoPlayer version in Giphy RN SDK. Unfortunately, I can't say exactly when we'll do it. 
But, If you don't use the Giphy clips feature in your app, you can update dependencies in your `build.gradle` file, for example:
 - add these lines to the dependencies section of the `build.gradle` file:
 ```
  implementation(“com.google.android.exoplayer:exoplayer-core:2.16.0”)
  implementation(“com.google.android.exoplayer:exoplayer-ui:2.16.0")
 ```
 - add the `resolutionStrategy` to the `configurations.all` section of the `build.gradle` file:
 ```
 configurations.all {
        resolutionStrategy {
            //  *replace existing forced modules with new ones:
            forcedModules = ['com.google.android.exoplayer:exoplayer-ui:2.16.0']
        }
    }
 ```
 
You may also find more information about dependency resolution in these comments:
- https://github.com/Giphy/giphy-android-sdk/issues/111#issuecomment-755991016
- https://github.com/Giphy/giphy-android-sdk/issues/111#issuecomment-756346152

**Comment by pshoniuk** [comment]
The ExoPlayer version has been updated in this release [v1.4.0](https://github.com/Giphy/giphy-react-native-sdk/releases/tag/v1.4.0)
