### ISSUE TITLE
Mismatch with exoplayer versions

### ISSUE THREAD

**Issue by CharlesCarey** [Giphy/giphy-react-native-sdk#49]
## 🐛 Bug Report

I have a react native project that uses `giphy-react-native-sdk` and `react-native-track-player` (https://github.com/DoubleSymmetry/react-native-track-player) . The mismatch in the exoplayer versions causes my app to crash on Android. `giphy-react-native-sdk` uses exoplayer 2.13.3, while`react-native-track-player` uses exoplayer 2.11.4. 

If I force exoplayer to be version 2.13.3 then `react-native-track-player` will crash because methods it relies on have changed between 2.11.4 => 2.13.3. Similarly, if I force the exoplayer version to 2.11.4 then `giphy-react-native-sdk` crashes with error: `java.lang.RuntimeException: Could not invoke GiphyReactNativeSDK.configure` which is caused by `Caused by: java.lang.ClassNotFoundException: com.google.android.exoplayer2.upstream.cache.CacheDataSource$Factory`.

I understand that it isn't normally possible for libraries with different exoplayer versions to coexist. I am hoping that you could give me some tips or pointers to help me fix this issue. I am more than happy to patch one of the libraries locally to fix this issue.

Thank you!

## To Reproduce

1. Have react native app with react-native-track-player@2.1.2 and @giphy/react-native-sdk@1.3.0
2. Start app on Android
3. See mismatch with exoplayer version causing app to crash

## Expected behavior

App launches without crashing.

## Actual Behavior

App crashes

## Your Environment

- Giphy React Native SDK version: 1.3.0
- React Native version: 0.66.3
- Platform(s): Android
- Device info (Simulator/Device? OS version? Debug/Release?): All android devices

**Comment by CharlesCarey** [comment]
I have made an additional bug report here - https://github.com/DoubleSymmetry/react-native-track-player/issues/1364.

**Comment by CharlesCarey** [comment]
Hey @pshoniuk! Thanks so much for getting back to me so quickly!

Yeah, I thought it might be quite tricky to have compatibility but I thought I would enquire just in case. I am currently relying on the vanilla gifs from Giphy, so I am happy to drop clip support from the Android version of my app in the short-term while I wait for `react-native-track-player` to move to a higher version of exoplayer.

Do you have any idea on when those changes will land? As I said earlier, I am happy to patch the package locally so I don't necessarily need a full on release, if that's easier.

Thanks again for all your help! Your library is extremely helpful and easy to use!

**Comment by pshoniuk** [comment]
We are going to release it tomorrow. I will update the status here when these changes are released.

**Comment by CharlesCarey** [comment]
It works! Thank you so much! You have been extremely helpful. I really was not expecting this level of help. I am very grateful!

**Comment by adriandiaz** [comment]
Hi @pshoniuk I'm trying to reference the link to the branch with the patch but it's broken. Can you send updated link? Thanks!
