### ISSUE TITLE
Giphy SDK Causes App Crashing

### ISSUE THREAD

**Issue by ethoman** [Giphy/giphy-react-native-sdk#56]
Hi Giphy Team,

I am posting this because the our engineering team has discovered that the giphy sdk is not stable and causes app crashing on iOS. We have error logs from user crashes, and they show that the culprit is the giphy sdk. Almost every log attached mentions Giphy or some part of Giphy by name. I have emailed your team with the logs, and also attached a zip of them at the bottom so you may investigate. For the time being, it seems we may have to remove giphy from our application.

We are currently using React Native version 0.67.1, node version 16.13.2, and giphy 1.5.0. Our build is currently on testflight, and works well for the most part except that the app crashes randomly every now and then when using the chat functionality (which is where our giphy implementation is located). Gifs successfully load, are able to be sent, and work exactly as they should. However, the app crashes randomly when using chat. As such, I can't provide exact steps to replicate because the crashing is arbitrary. Thanks for all the help, and I appreciate the support. Please let me know of any potential fixes for the situation, because we love using Giphy and we believe it adds great value to the app.

Thank you!

- Giphy React Native SDK version: 1.5.0
- React Native version: 0.67.1
- Platform(s) (iOS, Android, or both?): iOs
- Device info (Simulator/Device? OS version? Debug/Release?): Multiple iphones (iphone 12, iphone 12  pro, iphone 12 pro max)

Crash logs:
[Archive.zip](https://github.com/Giphy/giphy-react-native-sdk/files/7997745/Archive.zip)

**Comment by pshoniuk** [comment]
Hi @ethoman, thanks for the report!

We are currently trying to reproduce this issue and find the root cause. When we get new details, I'll update the status here. Also, if you get more information, please share it with us. It will be very helpful.

**Comment by ethoman** [comment]
Also, just got some crashing on version 1.4.1

**Comment by pshoniuk** [comment]
Yes, unfortunately, this problem is reproduced in older versions as well. But we have good news - we created a playground where this issue occurs very often. This allowed us to find the root of the problem, and we are currently working on the fix.

**Comment by mai-hu-mukesh-parmar** [comment]
TypeError: null is not an object (evaluating '_GiphySDK.NativeGiphySDK.configure')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:204:6 in guardedLoadModule
at http://192.168.29.81:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:215722:3 in global code



i m getting this issue can anybody help me out !

**Comment by pshoniuk** [comment]
Hi @mai-hu-mukesh-parmar. Giphy React Native SDK isn't currently compatible with Expo projects. It's because Expo's managed workflow doesn't allow React Native libraries that introduce their own native code.

But Expo projects can be updated to become compatible. You can learn more about how to do this here:

[Expo - Adding custom native code](https://docs.expo.dev/workflow/customizing)
[Expo - Using Third-Party Libraries](https://docs.expo.dev/workflow/using-libraries/#using-third-party-libraries)

**Comment by pshoniuk** [comment]
Hi @ethoman. We recently released Giphy RN SDK [1.7.0](https://github.com/Giphy/giphy-react-native-sdk/releases/tag/v1.7.0). This release includes fixes and performance improvements for the GiphyVideoView component and potentially fixes the problem described here. Please try this version when you get a chance.

**Comment by bryanltobing** [comment]
Hi @pshoniuk 

based on your comment here. is it still the case up until now?
> Hi @mai-hu-mukesh-parmar. Giphy React Native SDK isn't currently compatible with Expo projects. It's because Expo's managed workflow doesn't allow React Native libraries that introduce their own native code.

I already use Expo [development build](https://docs.expo.dev/develop/development-builds/introduction/), but I'm not sure if that's enough or if I should just use the [bare workflow](https://docs.expo.dev/bare/overview/) instead.

> But Expo projects can be updated to become compatible. You can learn more about how to do this here:

Could you please share the details on how to update my Expo project to support the 'giphy-rn-sdk'

**Comment by pshoniuk** [comment]
hi @bryanltobing 
We've added a new section to the documentation describing how to use the SDK with Expo: https://github.com/Giphy/giphy-react-native-sdk/blob/main/docs/expo-integration.md
