### ISSUE TITLE
Crash in Android (but not iOS) when react-native-video instances created

### ISSUE THREAD

**Issue by bumpingChris** [Giphy/giphy-react-native-sdk#57]
## 🐛 Bug Report

Hi Giphy Team, 

We are experiencing crashes in our Android build. 

When we install the Giphy SDK version 1.5.0 (yarn add @giphy/react-native-sdk@1.5.0) - even without implementing the GiphyDialog or any other Giphy services on our app (simply installing the SDK) - our Android app would crash when react-native-video instances are loaded. 

I suspect it has to do with exoplayer:
react-native-video (v5.2) expects exoplayer v2.13.2
@giphy/react-native-sdk (v1.5.0) expects explayer v2.16.0
So during the build, gradle autoupgrades the exoplayer to v2.16.0 which may cause the crash with react-native-video.

Crashlytics says:

Caused by java.lang.ClassNotFoundException
Didn't find class "com.google.android.exoplayer2.video.VideoListener" on path: DexPathList[[zip file "/data/app/~~UttTeZL9Ap7vBppOM40CKw==/com.bumping.app-gKQFsxEfMZfWnytPIJ7rMw==/base.apk"],nativeLibraryDirectories=[/data/app/~~UttTeZL9Ap7vBppOM40CKw==/com.bumping.app-gKQFsxEfMZfWnytPIJ7rMw==/lib/arm64, /data/app/~~UttTeZL9Ap7vBppOM40CKw==/com.bumping.app-gKQFsxEfMZfWnytPIJ7rMw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]

## To Reproduce

1. yarn add @giphy/react-native-sdk@1.5.0
1. Run app (which previously runs without issue)
1. App on startup loads a page in a tab (whose page is not shown) that contains a Flatlist with content containing react-native-videos. App crashes.  (Note that, if I removed (commented out) the react-native-video component - it does not crash)

## Expected behavior

Not crash

## Your Environment

- Giphy React Native SDK version: 1.5.0
- React Native version: 0.63.3 
- Platform(s) (iOS, Android, or both?): Android (works find on iOS)
- Device info (Simulator/Device? OS version? Debug/Release?): Crashes on both simulator on real device (debug and release)

**Comment by pshoniuk** [comment]
Hi @bumpingChris, thanks for the report!

Could you specify the version of react-native-video you are using?
