### ISSUE TITLE
Set rating level when using GiphyContent.search

### ISSUE THREAD

**Issue by chaaya** [Giphy/giphy-react-native-sdk#58]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Would be great to be able to set the rating level when using GiphyContent.search.
This works with the Web SDK. 

### Motivation 🔦

We are building an cross platform app for android, ios and web. We have built our custom Giphy experience by using the Search API in combination with GiphyGridView for native and Grid for web.

One requirement we are having in our app is that we need to set the rating to ensure that non disturbing gifs are shown to the user due to the reason that it is a business/enterprise app. 

As I said earlier, this works perfectly in web but it is missing in the native sdk.

**Comment by pshoniuk** [comment]
Hi @chaaya, thanks for reaching out. This is a good point. We will add this feature in an upcoming release. When it happens, I'll update the status here.
