### ISSUE TITLE
Crashing on Android

### ISSUE THREAD

**Issue by ethoman** [Giphy/giphy-react-native-sdk#61]
Hi Giphy Team,

I've reached out about a couple issues so far, so sorry for putting more work on your plate. Our team has decided to release our app on the android app store in addition to iOS. As such, we compiled the app into android. Unfortunately, the giphy sdk is throwing memory errors and making it impossible for us to compile the code on android. We have tried multiple versions of giphy, ranging from 1.4 to the most recent 1.7. All of them cause the same crash which renders our application unusuable. Are we doing anything wrong here? I'm providing screenshots of the errors.

## To Reproduce
1) Install giphy and implement it per your docs
2) Compile react native into android
3) Crash

## Expected behavior
We thought the app would run but it crashes from out of memory errors.

(Write what you thought would happen.)

## Actual Behavior

Crashes with the following:
Errors in giphy 1.4.1:
![image](https://user-images.githubusercontent.com/30179682/160207000-841b26ad-ad7e-4081-b0d0-b92ca12b2db4.png)
![image](https://user-images.githubusercontent.com/30179682/160207013-a8393a00-db6b-4c9b-8d63-1e9f426b0339.png)

Errors in giphy 1.7.0:
![image](https://user-images.githubusercontent.com/30179682/160207047-c7c34c47-123c-4b9a-b352-fbfa797b8629.png)
![image](https://user-images.githubusercontent.com/30179682/160207056-18562d9b-192c-4e77-ad9b-f2e757acd152.png)

## Your Environment
- Giphy React Native SDK version: 1.4 and 1.7 tried
- React Native version: 0.65.1, but have tried other versions as well
- Platform(s) (iOS, Android, or both?): android
- Device info (Simulator/Device? OS version? Debug/Release?): Not quite sure what my colleague used, can find out if necessary

**Comment by pshoniuk** [comment]
Hi, @ethoman thanks for reaching out. 

Do you use Android Studio when compiling the app for the Android platform? If yes, could you please share these settings?

![image](https://user-images.githubusercontent.com/20577736/160386468-d76c6e40-6c8e-4744-9629-f509dfa5a4a2.png)

**Comment by ethoman** [comment]
here they are:
![image](https://user-images.githubusercontent.com/30179682/160536372-92caff37-928d-4ccb-99c3-0f13693a4c4e.png)

**Comment by pshoniuk** [comment]
Hi, thanks for your reply. Then it may be a multidex issue. Please try adding
```
android {
    defaultConfig {
       multiDexEnabled true
    }
}
```

in the app `buid.gradle`
