### ISSUE TITLE
How to render GiphyMediaView without aspectRatio, knowing just id

### ISSUE THREAD

**Issue by mikhail-talkshoplive** [Giphy/giphy-react-native-sdk#65]
```
import React from 'react';
import { GiphyMediaView, GiphySDK } from '@giphy/react-native-sdk';
GiphySDK.configure({ apiKey: '***********' });
const CommentItem = ({ comment = {} }) => {
  return (
    <GiphyMediaView
      style={{ height: 50 }}
      renditionType={'FixedHeightSmall'}
      media={{
        id: 't64oxIpnQwF8ilGfZQ',
      }}
      autoPlay={true}
    />
  );
};

export default CommentItem;
```

![Simulator Screen Shot - iPhone 13 - 2022-06-17 at 00 10](https://user-images.githubusercontent.com/104591484/174164522-223010c7-1a61-4531-bd44-d6283aeb0609.png)

**Comment by pshoniuk** [comment]
Hi @mikhail-talkshoplive , thanks for reaching out.

The GIPHY RN SDK has no logic for scaling images when the aspect ratio is not specified. We have prepared a release candidate that should fix this problem. You can try this version [1.8.0-rc.0](https://www.npmjs.com/package/@giphy/react-native-sdk/v/1.8.0-rc.0) for testing. It would be great to get your feedback before we release v1.8.0.

**Comment by mikhail-talkshoplive** [comment]
> Hi @mikhail-talkshoplive , thanks for reaching out.
> 
> The GIPHY RN SDK has no logic for scaling images when the aspect ratio is not specified. We have prepared a release candidate that should fix this problem. You can try this version [1.8.0-rc.0](https://www.npmjs.com/package/@giphy/react-native-sdk/v/1.8.0-rc.0) for testing. It would be great to get your feedback before we release v1.8.0.

unfortunately same result, should I pass any specific props?  (test  id t64oxIpnQwF8ilGfZQ)

**Comment by pshoniuk** [comment]
In [1.8.0-rc.0](https://www.npmjs.com/package/@giphy/react-native-sdk/v/1.8.0-rc.0) we scale the content to fill the view bounds and maintain the aspect ratio. It works similarly to `"resizeMode": "cover"`. We will add a `resizeMode` property similar to what we have for the [Image component in React Native](https://reactnative.dev/docs/image#resizemode). I think we'll do it next week. Currently, you can work with the "cover" mode, for example:
```
const CommentItem = ({ comment = {} }) => {
  return (
    <GiphyMediaView
      style={{ height: 200, width: 200 }}
      renditionType={GiphyRendition.FixedHeightSmall}
      media={{
        id: 't64oxIpnQwF8ilGfZQ',
      }}
      autoPlay={true}
    />
  )
}
```

**Comment by mikhail-talkshoplive** [comment]
@pshoniuk your example works perfectly, thank you. resizeMode - it will be fantastic

**Comment by pshoniuk** [comment]
GIPHY RN SDK [v1.8.0](https://www.npmjs.com/package/@giphy/react-native-sdk/v/1.8.0) has been released. This version supports the [resizeMode property](https://github.com/Giphy/giphy-react-native-sdk/blob/main/docs/api.md#giphymediaview) for the GiphyMediaView component to determine how to resize an image when the frame does not match the size of the raw image.
