### ISSUE TITLE
Duplicate class expoplayer

### ISSUE THREAD

**Issue by suupham2506** [Giphy/giphy-react-native-sdk#66]
## 🐛 Bug Report

Duplicate class com.google.android.exoplayer2.video.spherical.TouchTracker found in modules jetified-exoplayer-core-2.16.0-runtime

## To Reproduce
<img width="572" alt="Screen Shot 2022-06-17 at 11 52 16" src="https://user-images.githubusercontent.com/28852565/174227463-fbb804a1-78c5-4aa0-a669-f7502216b586.png">

I use the latest version

## Your Environment

- Giphy React Native SDK version: latest one.^1.7.2
- React Native version: FILL THIS OUT : 0.68.2
- Platform(s) (iOS, Android, or both?): android
- Device info (Simulator/Device? OS version? Debug/Release?): Real device SamSung

**Comment by pshoniuk** [comment]
Hey @suupham2506, thanks for reaching out.

It looks like you are using several packages with different versions of ExoPlayer. You can try locking your dependencies in the `build.gradle` file. You can find more information in [this comment](https://github.com/Giphy/giphy-react-native-sdk/issues/48#issuecomment-999620625).  

If that didn't work for you, it would be very helpful to know the actual dependency tree of your project. You can run the `gradle app:dependencies` command from the android folder to bring it up in the console.
