### ISSUE TITLE
Sound suddenly starts playing out of no where

### ISSUE THREAD

**Issue by ramiel1999** [Giphy/giphy-react-native-sdk#69]
## 🐛 Bug Report

Giphy video is turning sound on suddenly when inside app or even when phone locked

## To Reproduce

If I am being honest I have no idea. I was just exploring the example app

## Expected behavior

play sound when explicitly turning it on

## Actual Behavior

Plays sound suddenly

https://user-images.githubusercontent.com/80689446/174854442-0b33f20d-91ce-407e-85b6-2d2a03c070d7.mp4

## Your Environment

- Giphy React Native SDK version:  1.8.0
- React Native version: 0.68.2
- Platform(s) (iOS, Android, or both?): Android, havent tried ios
- Device info (Simulator/Device? OS version? Debug/Release?):  Device/Android11/Debug

## Reproducible Demo

example app from repo

**Comment by pshoniuk** [comment]
Hi, @ramiel1999 thanks for reaching out.

It would be great if you could provide a little more detail. Did you change the code of the example app, or did you just run it on the device? Also, perhaps you can recall some of the actions you performed with the app before this issue occurred?

**Comment by ramiel1999** [comment]
The only thing I did was to edit some styling. The list showing selected gifs was given a max height, but I wanted to expand it to fill the screen.
I also commented the parts that use react-native-status-bar-height and react-native-picker cause I didnt have them installed and they are not needed for app functionality. That was it
