### ISSUE TITLE
Conflict with react-native-track-player

### ISSUE THREAD

**Issue by suupham2506** [Giphy/giphy-react-native-sdk#72]
## 🐛 Bug Report

Duplicate exoplayer

## Actual Behavior
(Write what happened. Add screenshots, if applicable.)

## Your Environment

- Giphy React Native SDK version: 1.9.0
- React Native version: 0.69.4
- React native track player version: 3.0.0
- Platform(s) (iOS, Android, or both?): Both
- Device info (Simulator/Device? OS version? Debug/Release?): Both simulator and real device

**Comment by pshoniuk** [comment]
Hi @suupham2506, thanks for the report!

This is an old issue. We are working on a solution allowing users to specify the ExoPlayer version, but unfortunately, there is not much we can do now. You can learn more about this issue in [this thread](https://github.com/Giphy/giphy-react-native-sdk/issues/49).
