### ISSUE TITLE
I have issue - _GiphySDK.NativeGiphySDK is undefined

### ISSUE THREAD

**Issue by Rananjaya** [Giphy/giphy-react-native-sdk#73]
I have this issue when using giphy react native sdk...

_GiphySDK.NativeGiphySDK is undefined

**Comment by Rananjaya** [comment]
Hi @pshoniuk  Im using  "react-native": "~0.63.4" for my project and im tested it on android 9.0.

**Comment by pshoniuk** [comment]
@Rananjaya I have not been able to reproduce this. If the problem is still relevant, could you please create and share a minimal playground where this problem occurs?

**Comment by pshoniuk** [comment]
I am going to close this issue. Please reopen it or open a new one if it is still relevant and you have additional details.

**Comment by Rananjaya** [comment]
any solution for this ?
