### ISSUE TITLE
GiphyMediaView sometimes renders GIF in incorrect ratio

### ISSUE THREAD

**Issue by hronnro** [Giphy/giphy-react-native-sdk#85]
## 🐛 Bug Report

I'm dealing with a UI bug, my hunch is that it might be related to GiphyMediaView but it's hard to tell as I’m using Sendbird React Native UIKit as a chat handler in my React Native app where we display the GIF so it's still a possibility the bug is on Sendbird end.

The bug is that only the last message (if it’s a GIF, does not happen for regular text or file messages) does not display in correct ratio, but as soon as there is a newer message in the chat, the GIF will render correctly. 

I think it’s best shown with an example (I’ve simplified my code a lot just to show that if I render any message as a GiphyMediaView the bug will appear.):

```
import {
  GiphyMediaView,
  GiphyRendition,
  ResizeMode,
} from "@giphy/react-native-sdk";
import {
  MessageRenderer,
  createGroupChannelFragment,
} from "@sendbird/uikit-react-native";

const GroupChannelFragment = createGroupChannelFragment();

 <GroupChannelFragment
      channel={channel}
      onPressHeaderLeft={() => {}}
      onPressHeaderRight={() => {}}
      onChannelDeleted={() => {}}
      renderMessage={() => (
        // I also tried playing around with renditionType/resizeMode but neither fixed the bug
        <GiphyMediaView
          style={{
            height: 100,
            width: 100,
          }}
          media={{
            id: "t64oxIpnQwF8ilGfZQ",
          }}
        />
```

 ![image](https://user-images.githubusercontent.com/7429825/195371869-4e99adc8-f416-456b-bcb5-b5351bafbceb.png)

_**Notice how the last GIF does not fill in 100x100**_

If I however display a simple 100x100 red square for each message, it will not cut the view (indicating it’s not a Sendbird bug?)

```
 <GroupChannelFragment
      channel={channel}
      onPressHeaderLeft={() => {}}
      onPressHeaderRight={() => {}}
      onChannelDeleted={() => {}}
      renderMessage={() => (
        <View
          style={{
            width: 100,
            height: 100,
            borderColor: "red",
            borderWidth: 1,
          }}
        />
      )}
    />
```

![Pasted Graphic 1](https://user-images.githubusercontent.com/7429825/195369209-8afef295-b83d-4d47-953e-5702e2fe839f.png)

And lastly here is a video showing the bug in action (I put a purple view on the parent to emphasize how big the GIF should be) and then how it’s fixed when a new message is displayed.

Here is how I actually display the GIF (as seen in the video)
```
   <GiphyMediaView
        media={{ id: encodeGif.id as string }}
        resizeMode={ResizeMode.Contain}
        renditionType={GiphyRendition.FixedWidth}
        style={{
          height: encodeGif.images?.fixed_width?.height || 200,
          width: encodeGif.images?.fixed_width?.width || 200,
          borderRadius: 8,
          overflow: "hidden",
        }}
    />
```

https://user-images.githubusercontent.com/7429825/195376148-554ab739-29ac-40e2-a10e-3380237f34a5.mov

Do you have any idea what might be happening? 
Thanks for reading and let me know if you need any more information! 🫶

## Your Environment

- Giphy React Native SDK version: "1.11.1"
- React Native version: "0.69.5"
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator iPhone 13 Pro
- @sendbird/uikit-react-native: "1.1.2",

**Comment by pshoniuk** [comment]
Hi, @hronnro. Thanks for reaching out.

I tried reproducing this issue with this [SendBird sample](https://github.com/sendbird/sendbird-uikit-react-native/tree/main/sample). But in this sample, everything works as expected. I think it's because this example includes a header that, under the hood, adds padding to avoid overlapping the status bar.
<img src="https://user-images.githubusercontent.com/20577736/195562892-889ea443-1d7a-45d1-99f9-1a0037c3eb58.png" width="300"/>

To mimic your case, I removed the header and added a margin to the flatList. This helped me solve the problem. I think you can also try something similar:
```jsx
const { top } = useSafeAreaInsets();

return (
    <GroupChannelFragment
        channel={channel}
        onPressHeaderLeft={() => {}}
        onPressHeaderRight={() => {}}
        onChannelDeleted={() => {}}
        flatListProps={{ style: {marginTop: top} }}
        renderMessage={() => (
            <GiphyMediaView
                style={{ height: 100, width: 100 }}
                media={{ id: 't64oxIpnQwF8ilGfZQ' }}
            />
        )}
    />
);
```
<img src="https://user-images.githubusercontent.com/20577736/195564423-c27a2750-ab72-42e8-a4a4-2badadfdb01f.png" width="350"/>

**Comment by hronnro** [comment]
That was it! Oh wow thank you so much, I'm sorry this wasn't even a problem with Giphy 🥲 

Have a good one ☺️
