### ISSUE TITLE
[GiphyDialog] Default showCheckeredBackground not working

### ISSUE THREAD

**Issue by Cebri63** [Giphy/giphy-react-native-sdk#87]
## 🐛 Bug Report

ONLY ON ANDROID 

In the documentation, `showCheckeredBackground` for `GiphyDialog` is supposed to be `false` by default. 
But on my screen, I see the checkered background on all the stickers. 
I've manually set this option to `false` like that : 

```js
GiphyDialog.configure({
  showCheckeredBackground: false,
});
```

but it doesn't change anything. 

## Your Environment

- Giphy React Native SDK version:  "1.7.0",
- React Native version: "0.66.4"
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): All android devices, debug and release

**Comment by pshoniuk** [comment]
Hi @Cebri63, Thanks for reaching out.

`GiphyDialog.configure({ showCheckeredBackground: false });` only disables a checkered background for the GiphyDialog. Have you tried to specify the [showCheckeredBackground property](https://github.com/Giphy/giphy-react-native-sdk/blob/main/docs/api.md#giphymediaview) for the GiphyMediaView component?
