### ISSUE TITLE
Hide Trending From GiphyDialog

### ISSUE THREAD

**Issue by daman-talkshoplive** [Giphy/giphy-react-native-sdk#88]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

It would be great if there was a way to hide Trending list from GiphyDialog. 
With something like:
`GiphyDialog.configure({
  requestType: [GiphyContentRequestType.Search, GiphyContentRequestType.Recents],
})`

**Comment by pshoniuk** [comment]
Hey @daman-talkshoplive 

Unfortunately, we don't currently support this use case in the GiphyDialog. However, you can achieve the experience you describe with the [GiphyGridView component](https://github.com/Giphy/giphy-react-native-sdk/blob/main/docs/api.md#giphygridview), which allows for more customization. 

I've passed your feedback on to my team for future consideration.
