### ISSUE TITLE
iOS bottom row theme is wrong when device is in dark mode but theme prop is "light"

### ISSUE THREAD

**Issue by efstathiosntonas** [Giphy/giphy-react-native-sdk#89]
## 🐛 Bug Report

iOS bottom row theme is wrong when device is in dark mode but `theme` prop is `light`.

## To Reproduce

(Write your steps here:)

1. Set iPhone on dark mode from settings
1. Use `light` theme prop on `GiphyDialog`
1. Bottom row colors and background are wrong (sickers, emojis etc)

## Expected behavior

 I'm expecting the bottom row to be the same like when device is in light theme mode.

## Actual Behavior

 Bottom row colors are wrong when device is in dark mode but the `theme` prop is `light`. Please see attached screenshots and device theme/prop theme combos:

This is Device in dark mode,  `theme` prop is `light`:

<img width="603" alt="Screenshot 2022-12-13 at 08 55 55" src="https://user-images.githubusercontent.com/717975/207247381-6f076a6b-287c-4c62-8827-fb1ede734b4d.png">

This is device light mode,  `theme` prop `light`:

<img width="594" alt="Screenshot 2022-12-13 at 08 56 56" src="https://user-images.githubusercontent.com/717975/207247483-0a49ac76-20b7-456a-bb52-29e82612028d.png">

this is device light mode,  `theme` prop `dark`:

<img width="583" alt="Screenshot 2022-12-13 at 08 58 29" src="https://user-images.githubusercontent.com/717975/207247762-c7da7704-7887-4d94-86b3-d0c3b013e9e9.png">

this is device dark mode,  `theme` prop `dark`:

<img width="679" alt="Screenshot 2022-12-13 at 08 59 09" src="https://user-images.githubusercontent.com/717975/207247884-f8547f2a-9cfb-4deb-b4d3-99cb331434c5.png">

## Your Environment

- Giphy React Native SDK version: `2.1.0`
- React Native version: `0.68.5`
- Platform(s) (iOS, Android, or both?): ios `16.1`
- Device info (Simulator/Device? OS version? Debug/Release?):  iPhone 13 iOS `16.1`

**Comment by pshoniuk** [comment]
Hi @efstathiosntonas, thank you for the detailed report.
We will release a fix in the next version. When it becomes available, I will post the update here.

**Comment by efstathiosntonas** [comment]
Hi @pshoniuk, any updated on this one? Thanks

**Comment by efstathiosntonas** [comment]
Great, thanks!

**Comment by efstathiosntonas** [comment]
Hi @pshoniuk, thanks, will try it asap.

**Comment by efstathiosntonas** [comment]
@pshoniuk totally forgot about it, it works as it should now, thanks for closing it.

**Comment by pshoniuk** [comment]
Don't worry. It's nice to hear that everything is working as expected!
