### ISSUE TITLE
Change the theme of the initial giphies shown

### ISSUE THREAD

**Issue by chr4ss12** [Giphy/giphy-react-native-sdk#96]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Am not entirely sure if this exists or not,

but we would like to have a functionality where we can specify which initial giphies would be shown when the GiphyDialog is first opened.

We plan to make our own giphy channel with some cool gifs that are focused on a concrete theme, and would like to do something a long of the lines of:

```
<GiphyDialog defaultSearchQuery="@myChannelID"
```

which uses the giphy search query to show giphies from specific channel

**Comment by pshoniuk** [comment]
Hi @chr4ss12
Thanks for your feedback! Unfortunately, it's not currently possible to change the initial content from the GIPHY trending feed if your integration relies on the pre-designed GIPHY Template UIs. I've passed your request to my team for future consideration. 
The [grid-only solution](https://github.com/Giphy/giphy-react-native-sdk/blob/main/docs/api.md#giphygridview) provides more flexibility as to how the grid is populated. However, it's worth considering how GIPHY invests significant effort in ensuring the trending feed consists of engaging content relevant to a broad variety of use cases. 
Sorry we couldn't be of more help here. Thanks for using the GIPHY SDK.
