### ISSUE TITLE
GiphyGridView text customisation

### ISSUE THREAD

**Issue by topheroes** [Giphy/giphy-react-native-sdk#97]
Hello,

Is there a way to customise the 'No GIFs found' text? For example how to make it change colour when the theme (dark, light) changes?

**Comment by pshoniuk** [comment]
Hi @topheroes, thanks for reaching out.
We don't have an API to customize the "No GIFs found" text. But we plan to add this feature in an upcoming release. We'll keep you posted on when this happens.

**Comment by pshoniuk** [comment]
Hi @topheroes 
We have just released RN SDK [v2.4.0](https://github.com/Giphy/giphy-react-native-sdk/releases/tag/v2.4.0), which comes with enhanced [theme support](https://github.com/Giphy/giphy-react-native-sdk/blob/main/docs/api.md#giphytheme) for GiphyDialog and GiphyGridView. While we currently don't offer options to customize the text you mentioned, you can check the [defaultTextColor theme](https://github.com/Giphy/giphy-react-native-sdk/blob/main/docs/api.md#giphytheme) property. This property allows you to modify the default text color, affecting the text you mentioned.
