### ISSUE TITLE
GiphyMediaView not show gif generated from keyword (iOS)

### ISSUE THREAD

**Issue by danhddao1997** [Giphy/giphy-react-native-sdk#98]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

## To Reproduce

(Write your steps here:)

1. Run app, open Giphy Model, type keyword and click on the highlighted place 
![image](https://user-images.githubusercontent.com/91647959/230113558-b041c4f6-1a46-41e9-9ea7-ca34bcf3cf50.png)
3. Choose one of the generated gif
![simulator_screenshot_AEFB291B-5F18-42FB-9488-B45D3E8A16E8](https://user-images.githubusercontent.com/91647959/230113818-74d0e911-398a-4fc7-a69c-83017e4c126a.png)

## Expected behavior
The gif file show below the button (like this)
![simulator_screenshot_D2F125A1-3C25-4753-A31C-2AFDD33E4D0F](https://user-images.githubusercontent.com/91647959/230114282-191adcee-3749-40b5-a4bc-159153a0624a.png)

## Actual Behavior
The gif file not show below the button

## Your Environment

- Giphy React Native SDK version: 2.1.3
- React Native version: 0.71.6
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): ios Simulator 16.2, ios Device 16.3

## Reproducible Demo
[GiphyMediaView API](https://github.com/Giphy/giphy-react-native-sdk/blob/main/docs/api.md#giphymediaview) (Basic usage)

**Comment by pshoniuk** [comment]
Hi @danhddao1997
Thank you for the report. We reproduced the issue on our side. I will let you know as soon as I get more details.
