### ISSUE TITLE
Selected content type on iOS ?

### ISSUE THREAD

**Issue by sonnguyen2000-github** [Giphy/giphy-react-native-sdk#99]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Can we add selectedContentType to support iOS also (working only on Android) ?

**Comment by pshoniuk** [comment]
Hi @sonnguyen2000-github, thanks for reaching out.
We released the GIPHY RN SDK [v2.2.0](https://www.npmjs.com/package/@giphy/react-native-sdk/v/2.2.0). In this version, we also added support for `selectedContentType` on iOS. So now it should work on both platforms.
